# Generated by Django 3.0.3 on 2020-03-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(max_length=50)),
                ('M_released_date', models.DateField()),
                ('M_languages', models.CharField(max_length=30)),
                ('M_img', models.ImageField(upload_to='movie_poster/')),
                ('M_quality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_story', models.CharField(max_length=500)),
                ('M_time_length', models.DurationField()),
                ('M_Categories', models.CharField(max_length=50)),
                ('M_format', models.CharField(max_length=10)),
                ('M_creator', models.CharField(max_length=20)),
                ('M_pics', models.ImageField(upload_to='movie_pics')),
                ('movie_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_apps.Movie_info')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_480p', models.FileField(upload_to='_480p')),
                ('_720p', models.FileField(default='None', upload_to='_720p/')),
                ('_1080p', models.FileField(default='None', upload_to='_1080p')),
                ('movie_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_apps.Movie_info')),
            ],
        ),
        migrations.CreateModel(
            name='M_screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot1', models.ImageField(default='None', upload_to='img1')),
                ('screenshot2', models.ImageField(default='None', upload_to='img2')),
                ('screenshot3', models.ImageField(default='None', upload_to='img3')),
                ('movie_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_apps.Movie_info')),
            ],
        ),
    ]
