# Generated by Django 3.1.5 on 2021-01-16 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='released_date',
            new_name='Released_date',
        ),
        migrations.AlterField(
            model_name='movie_file',
            name='File',
            field=models.FileField(upload_to='movie_file/'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 8, 21, 24, 858834)),
        ),
    ]
