# Generated by Django 3.0.3 on 2020-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_info',
            name='M_type',
            field=models.CharField(default='movie', max_length=15),
        ),
    ]
