# Generated by Django 3.0.3 on 2020-03-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0002_movie_info_m_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_msg', models.CharField(max_length=100)),
                ('U_Email_id', models.EmailField(max_length=254)),
                ('U_name', models.CharField(max_length=25)),
                ('movie_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_apps.Movie_info')),
            ],
        ),
    ]
