# Generated by Django 3.1.5 on 2021-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0002_auto_20210116_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Big_Poster',
            field=models.ImageField(default='None', upload_to='movie_poster/'),
        ),
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
