# Generated by Django 3.0.3 on 2020-03-29 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0003_usercomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='cmt_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 15, 16, 21, 171447)),
        ),
    ]
