# Generated by Django 3.0.3 on 2020-03-31 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0004_usercomments_cmt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('movie_name', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='cmt_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 18, 31, 26, 288483)),
        ),
    ]
