# Generated by Django 3.0.3 on 2020-04-03 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0006_auto_20200403_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='cmt_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 17, 0, 44, 675760)),
        ),
    ]
