# Generated by Django 3.0.3 on 2020-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=30)),
                ('e_no', models.IntegerField()),
                ('e_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=25)),
                ('released_date', models.DateField()),
                ('poster', models.ImageField(upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Series_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons', models.IntegerField()),
                ('storyline', models.CharField(max_length=300)),
                ('categories', models.CharField(max_length=30)),
                ('creator', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=10)),
                ('poster', models.ImageField(upload_to='poster/')),
                ('web_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Series_app.Web_series')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.IntegerField()),
                ('total_episodes', models.IntegerField()),
                ('episodes_name', models.CharField(max_length=300)),
                ('web_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Series_app.Web_series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_480p', models.FileField(default='none', upload_to='_480p/')),
                ('_720p', models.FileField(default='none', upload_to='_720p/')),
                ('_1080p', models.FileField(default='none', upload_to='_1080p/')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Series_app.Episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Series_app.Seasons'),
        ),
    ]
