# Generated by Django 3.0.3 on 2020-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series_info',
            old_name='poster',
            new_name='poster_img',
        ),
    ]
