# Generated by Django 3.0.3 on 2020-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0003_auto_20200403_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series_info',
            name='poster_img',
        ),
        migrations.AddField(
            model_name='series_info',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster_pic/'),
        ),
    ]
