# Generated by Django 3.0.3 on 2020-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0004_auto_20200403_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_series',
            old_name='poster',
            new_name='series_poster',
        ),
    ]
