# Generated by Django 3.0.3 on 2020-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0005_auto_20200403_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_info',
            name='series_img',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
