# Generated by Django 3.0.3 on 2020-04-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0006_series_info_series_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series_info',
            name='series_img',
        ),
    ]
