# Generated by Django 3.0.3 on 2020-04-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0007_remove_series_info_series_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='quality',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='series_info',
            name='actors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series_info',
            name='director',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
