# Generated by Django 3.0.3 on 2020-04-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0008_auto_20200403_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_poster', models.ImageField(upload_to='seasons_poster/')),
                ('s_screenshot1', models.ImageField(upload_to='screenshot3/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Series_app.Seasons')),
            ],
        ),
    ]
