# Generated by Django 3.0.3 on 2020-04-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0010_auto_20200404_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode_file',
            name='_720px',
        ),
        migrations.AddField(
            model_name='episode_file',
            name='_720p',
            field=models.FileField(default='none', upload_to='_720px/'),
        ),
    ]
