# Generated by Django 3.0.3 on 2020-04-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Series_app', '0013_season_pics_web_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode_file',
            name='_720p',
            field=models.FileField(default='none', upload_to='_720p/'),
        ),
    ]
